inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\afghanistan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Afghanistan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\afghanistan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\afghanistan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\albania.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Albania.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\albania.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\albania.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\algeria.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Algeria.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\algeria.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\algeria.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\andorra.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Andorra.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\andorra.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\andorra.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\angola.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Angola.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\angola.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\angola.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\antigua_and_barbuda.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Antigua_and_Barbuda.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\antigua_and_barbuda.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\antigua_and_barbuda.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\argentina.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Argentina.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\argentina.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\argentina.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\armenia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Armenia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\armenia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\armenia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\australia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Australia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\australia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\australia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\austria.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Austria.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\austria.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\austria.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\azerbaijan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Azerbaijan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\azerbaijan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\azerbaijan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bahrain.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bahrain.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bahrain.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bahrain.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bangladesh.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bangladesh.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bangladesh.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bangladesh.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\barbados.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Barbados.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\barbados.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\barbados.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belarus.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Belarus.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\belarus.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belarus.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belgium.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Belgium.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\belgium.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belgium.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belize.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Belize.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\belize.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\belize.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\benin.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Benin.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\benin.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\benin.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bhutan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bhutan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bhutan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bhutan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bolivia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bolivia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bolivia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bolivia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bosnia_and_herzegovina.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bosnia_and_Herzegovina.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bosnia_and_herzegovina.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bosnia_and_herzegovina.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\botswana.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Botswana.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\botswana.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\botswana.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\brazil.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Brazil.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\brazil.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\brazil.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\brunei.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Brunei.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\brunei.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\brunei.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bulgaria.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Bulgaria.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\bulgaria.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\bulgaria.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\burkina_faso.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Burkina_Faso.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\burkina_faso.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\burkina_faso.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\burundi.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Burundi.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\burundi.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\burundi.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cambodia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Cambodia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\cambodia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cambodia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cameroon.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Cameroon.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\cameroon.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cameroon.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\canada_(pantone).pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Canada_(Pantone).svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\canada_(pantone).png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\canada_(pantone).pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cape_verde.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Cape_Verde.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\cape_verde.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cape_verde.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\chad.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Chad.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\chad.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\chad.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\chile.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Chile.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\chile.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\chile.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\colombia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Colombia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\colombia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\colombia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\costa_rica.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Costa_Rica.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\costa_rica.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\costa_rica.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\croatia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Croatia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\croatia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\croatia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cuba.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Cuba.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\cuba.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cuba.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cyprus.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Cyprus.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\cyprus.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\cyprus.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\côte_d'ivoire.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Côte_d'Ivoire.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\côte_d'ivoire.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\côte_d'ivoire.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\denmark.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Denmark.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\denmark.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\denmark.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\djibouti.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Djibouti.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\djibouti.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\djibouti.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\dominica.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Dominica.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\dominica.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\dominica.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\east_timor.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_East_Timor.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\east_timor.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\east_timor.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ecuador.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Ecuador.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\ecuador.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ecuador.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\egypt.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Egypt.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\egypt.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\egypt.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\el_salvador.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_El_Salvador.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\el_salvador.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\el_salvador.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\equatorial_guinea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Equatorial_Guinea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\equatorial_guinea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\equatorial_guinea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\eritrea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Eritrea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\eritrea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\eritrea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\estonia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Estonia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\estonia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\estonia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\eswatini.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Eswatini.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\eswatini.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\eswatini.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ethiopia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Ethiopia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\ethiopia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ethiopia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\fiji.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Fiji.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\fiji.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\fiji.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\finland.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Finland.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\finland.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\finland.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\france.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_France.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\france.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\france.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\gabon.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Gabon.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\gabon.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\gabon.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\georgia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Georgia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\georgia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\georgia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\germany.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Germany.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\germany.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\germany.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ghana.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Ghana.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\ghana.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ghana.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\greece.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Greece.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\greece.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\greece.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\grenada.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Grenada.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\grenada.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\grenada.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guatemala.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Guatemala.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\guatemala.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guatemala.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guinea-bissau.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Guinea-Bissau.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\guinea-bissau.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guinea-bissau.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guinea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Guinea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\guinea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guinea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guyana.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Guyana.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\guyana.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\guyana.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\haiti.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Haiti.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\haiti.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\haiti.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\honduras.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Honduras.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\honduras.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\honduras.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\hungary.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Hungary.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\hungary.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\hungary.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iceland.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Iceland.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\iceland.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iceland.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\india.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_India.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\india.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\india.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\indonesia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Indonesia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\indonesia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\indonesia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iran.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Iran.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\iran.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iran.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iraq.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Iraq.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\iraq.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\iraq.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ireland.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Ireland.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\ireland.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ireland.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\israel.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Israel.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\israel.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\israel.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\italy.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Italy.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\italy.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\italy.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\jamaica.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Jamaica.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\jamaica.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\jamaica.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\japan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Japan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\japan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\japan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\jordan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Jordan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\jordan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\jordan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kazakhstan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Kazakhstan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\kazakhstan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kazakhstan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kenya.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Kenya.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\kenya.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kenya.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kiribati.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Kiribati.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\kiribati.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kiribati.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kuwait.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Kuwait.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\kuwait.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kuwait.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kyrgyzstan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Kyrgyzstan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\kyrgyzstan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\kyrgyzstan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\laos.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Laos.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\laos.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\laos.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\latvia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Latvia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\latvia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\latvia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lebanon.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Lebanon.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\lebanon.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lebanon.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lesotho.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Lesotho.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\lesotho.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lesotho.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\liberia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Liberia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\liberia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\liberia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\libya.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Libya.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\libya.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\libya.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\liechtenstein.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Liechtenstein.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\liechtenstein.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\liechtenstein.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lithuania.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Lithuania.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\lithuania.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\lithuania.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\luxembourg.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Luxembourg.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\luxembourg.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\luxembourg.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\madagascar.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Madagascar.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\madagascar.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\madagascar.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malawi.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Malawi.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\malawi.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malawi.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malaysia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Malaysia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\malaysia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malaysia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\maldives.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Maldives.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\maldives.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\maldives.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mali.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mali.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mali.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mali.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malta.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Malta.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\malta.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\malta.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mauritania.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mauritania.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mauritania.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mauritania.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mauritius.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mauritius.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mauritius.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mauritius.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mexico.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mexico.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mexico.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mexico.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\moldova.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Moldova.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\moldova.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\moldova.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\monaco.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Monaco.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\monaco.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\monaco.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mongolia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mongolia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mongolia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mongolia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\montenegro.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Montenegro.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\montenegro.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\montenegro.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\morocco.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Morocco.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\morocco.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\morocco.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mozambique.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Mozambique.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\mozambique.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\mozambique.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\myanmar.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Myanmar.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\myanmar.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\myanmar.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\namibia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Namibia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\namibia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\namibia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nauru.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Nauru.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\nauru.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nauru.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nepal.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Nepal.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\nepal.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nepal.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\new_zealand.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_New_Zealand.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\new_zealand.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\new_zealand.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nicaragua.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Nicaragua.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\nicaragua.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nicaragua.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\niger.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Niger.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\niger.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\niger.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nigeria.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Nigeria.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\nigeria.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\nigeria.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\north_korea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_North_Korea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\north_korea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\north_korea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\north_macedonia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_North_Macedonia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\north_macedonia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\north_macedonia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\norway.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Norway.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\norway.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\norway.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\oman.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Oman.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\oman.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\oman.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\pakistan (1).pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Pakistan (1).svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\pakistan (1).png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\pakistan (1).pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\pakistan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Pakistan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\pakistan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\pakistan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\palau.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Palau.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\palau.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\palau.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\palestine.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Palestine.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\palestine.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\palestine.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\panama.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Panama.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\panama.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\panama.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\papua_new_guinea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Papua_New_Guinea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\papua_new_guinea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\papua_new_guinea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\paraguay.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Paraguay.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\paraguay.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\paraguay.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\peru.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Peru.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\peru.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\peru.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\poland.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Poland.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\poland.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\poland.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\portugal.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Portugal.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\portugal.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\portugal.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\qatar.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Qatar.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\qatar.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\qatar.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\romania.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Romania.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\romania.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\romania.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\russia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Russia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\russia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\russia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\rwanda.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Rwanda.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\rwanda.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\rwanda.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_kitts_and_nevis.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Saint_Kitts_and_Nevis.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\saint_kitts_and_nevis.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_kitts_and_nevis.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_lucia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Saint_Lucia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\saint_lucia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_lucia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_vincent_and_the_grenadines.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Saint_Vincent_and_the_Grenadines.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\saint_vincent_and_the_grenadines.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saint_vincent_and_the_grenadines.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\samoa.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Samoa.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\samoa.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\samoa.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\san_marino.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_San_Marino.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\san_marino.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\san_marino.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sao_tome_and_principe.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Sao_Tome_and_Principe.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\sao_tome_and_principe.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sao_tome_and_principe.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saudi_arabia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Saudi_Arabia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\saudi_arabia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\saudi_arabia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\senegal.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Senegal.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\senegal.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\senegal.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\serbia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Serbia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\serbia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\serbia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\seychelles.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Seychelles.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\seychelles.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\seychelles.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sierra_leone.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Sierra_Leone.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\sierra_leone.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sierra_leone.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\singapore.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Singapore.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\singapore.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\singapore.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\slovakia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Slovakia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\slovakia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\slovakia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\slovenia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Slovenia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\slovenia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\slovenia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\somalia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Somalia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\somalia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\somalia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_africa.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_South_Africa.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\south_africa.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_africa.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_korea.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_South_Korea.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\south_korea.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_korea.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_sudan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_South_Sudan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\south_sudan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\south_sudan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\spain.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Spain.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\spain.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\spain.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sri_lanka.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Sri_Lanka.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\sri_lanka.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sri_lanka.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sudan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Sudan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\sudan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sudan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\suriname.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Suriname.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\suriname.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\suriname.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sweden.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Sweden.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\sweden.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\sweden.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\switzerland.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Switzerland.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\switzerland.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\switzerland.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\syria.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Syria.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\syria.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\syria.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tajikistan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Tajikistan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\tajikistan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tajikistan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tanzania.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Tanzania.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\tanzania.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tanzania.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\thailand.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Thailand.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\thailand.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\thailand.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_bahamas.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Bahamas.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_bahamas.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_bahamas.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_central_african_republic.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Central_African_Republic.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_central_african_republic.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_central_african_republic.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_comoros.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Comoros.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_comoros.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_comoros.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_czech_republic.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Czech_Republic.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_czech_republic.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_czech_republic.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_democratic_republic_of_the_congo.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Democratic_Republic_of_the_Congo.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_democratic_republic_of_the_congo.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_democratic_republic_of_the_congo.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_dominican_republic.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Dominican_Republic.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_dominican_republic.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_dominican_republic.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_federated_states_of_micronesia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Federated_States_of_Micronesia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_federated_states_of_micronesia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_federated_states_of_micronesia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_gambia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_The_Gambia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_gambia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_gambia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_marshall_islands.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Marshall_Islands.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_marshall_islands.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_marshall_islands.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_netherlands.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Netherlands.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_netherlands.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_netherlands.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_people's_republic_of_china.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_People's_Republic_of_China.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_people's_republic_of_china.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_people's_republic_of_china.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_philippines.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Philippines.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_philippines.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_philippines.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_republic_of_the_congo.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Republic_of_the_Congo.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_republic_of_the_congo.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_republic_of_the_congo.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_solomon_islands.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Solomon_Islands.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_solomon_islands.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_solomon_islands.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_arab_emirates.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_United_Arab_Emirates.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_united_arab_emirates.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_arab_emirates.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_kingdom.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_United_Kingdom.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_united_kingdom.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_kingdom.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_states.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_United_States.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_united_states.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_united_states.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_vatican_city.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_the_Vatican_City.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\the_vatican_city.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\the_vatican_city.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\togo.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Togo.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\togo.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\togo.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tonga.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Tonga.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\tonga.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tonga.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\trinidad_and_tobago.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Trinidad_and_Tobago.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\trinidad_and_tobago.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\trinidad_and_tobago.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tunisia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Tunisia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\tunisia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tunisia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\turkey.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Turkey.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\turkey.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\turkey.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\turkmenistan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Turkmenistan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\turkmenistan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\turkmenistan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tuvalu.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Tuvalu.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\tuvalu.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\tuvalu.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uganda.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Uganda.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\uganda.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uganda.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ukraine.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Ukraine.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\ukraine.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\ukraine.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uruguay.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Uruguay.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\uruguay.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uruguay.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uzbekistan.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Uzbekistan.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\uzbekistan.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\uzbekistan.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\vanuatu.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Vanuatu.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\vanuatu.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\vanuatu.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\venezuela.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Venezuela.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\venezuela.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\venezuela.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\vietnam.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Vietnam.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\vietnam.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\vietnam.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\yemen.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Yemen.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\yemen.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\yemen.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\zambia.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Zambia.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\zambia.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\zambia.pdf
inkscape --export-pdf=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\zimbabwe.pdf -z -f C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\svg\Flag_of_Zimbabwe.svg
gswin64.exe -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r72 -dGraphicsAlphaBits=1 -sOutputFile=C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\png\zimbabwe.png C:\Users\hornu\OneDrive\Documents\repos\flags\data\clean-data\images\pdf\zimbabwe.pdf